src/Entity/Task.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\Table;
use Doctrine\Persistence\PropertyChangedListener;

#[Entity()]
#[Table(name: 'app_task_items')]
class Task
{
    private $listeners = [];

    #[Id()]
    #[GeneratedValue(strategy: 'AUTO')]
    #[Column(type: 'bigint', options: ['unsigned' => true])]
    private int|null $id;

    #[ManyToOne(targetEntity: TaskList::class, inversedBy: "items")]
    private $taskList;

    #[Column(type: 'string', options: ['length' => 255])]
    private string $summary;

    #[Column(type: 'boolean')]
    private bool $done;

    #[Column(type: 'datetime_immutable')]
    private $created;

    /**
     * @internal New TaskItems should only be generated through TaskList::addItem()
     */
    public function __construct(TaskList $taskList, string $summary)
    {
        $this->taskList = $taskList;
        $this->summary = $summary;

        $this->done = false;
        $this->created = new DateTimeImmutable();
    }

    public function reopen(): void
    {
        if ($this->done === false) {
            throw new \RuntimeException('Task is already open.');
        }

        //$this->notifyListeners('done', true, false);
        $this->done = false;
    }

    public function close(): void
    {
        if ($this->done === true) {
            throw new \RuntimeException('Task is already done.');
        }

        $this->notifyListeners('done', false, true);
        $this->done = true;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getList(): TaskList
    {
        return $this->taskList;
    }

    public function getSummary(): string
    {
        return $this->summary;
    }

    public function isDone(): bool
    {
        return $this->done;
    }

    public function getCreatedOn(): DateTimeImmutable
    {
        return $this->created;
    }

    private function notifyListeners(string $propertyName, $oldValue, $newValue): void
    {
        foreach ($this->listeners as $listener) {
            $listener->propertyChanged($this, $propertyName, $oldValue, $newValue);
        }
    }

    public function addPropertyChangedListener(PropertyChangedListener $listener): void
    {
        $this->listeners[] = $listener;
    }

    public function setDone(bool $done): void
    {
        $this->done = $done;
    }

    public function setCreated(DateTimeImmutable $created): void
    {
        $this->created = $created;
    }
}

src/Entity/TaskList.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\Version;

#[Entity()]
#[Table(name: 'app_task_lists')]
class TaskList
{
    #[Id()]
    #[GeneratedValue(strategy: 'AUTO')]
    #[Column(type: 'bigint', options: ['unsigned' => true])]
    private int|null $id;


    #[Version]
    #[Column(type: 'integer', options: ['unsigned' => true])]
    private int $version;

    #[ManyToOne(targetEntity: User::class)]
    #[JoinColumn(nullable: false)]
    private User $owner;

    #[Column]
    private string $title;

    #[Column(type: 'boolean')]
    private bool $archived;

    #[OneToMany(targetEntity: Task::class, mappedBy: "taskList", cascade: ['persist'])]
    private $items;

    #[ManyToMany(targetEntity: User::class)]
    private $contributors;

    #[Column(type: "datetime_immutable")]
    private DateTimeImmutable $created;

    #[Column(type: "datetime_immutable", nullable: true)]
    private ?DateTimeImmutable $lastUpdated = null;

    public function __construct(User $owner, string $title)
    {
        $this->owner = $owner;
        $this->title = $title;

        $this->archived = false;
        $this->created = new DateTimeImmutable();
        $this->items = new ArrayCollection();
        $this->contributors = new ArrayCollection();
    }

    public function archive(): void
    {
        $this->archived = true;
    }

    public function addItem(string $summary): void
    {
        $this->items->add(new Task($this, $summary));
    }

    public function addContributor(User $user): void
    {
        $this->contributors->add($user);
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getVersion(): int
    {
        return $this->version;
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function isArchived(): bool
    {
        return $this->archived === true;
    }

    public function getItems(): array
    {
        return $this->items->toArray();
    }

    /**
     * @return User[]
     */
    public function getContributors(): array
    {
        return $this->contributors->toArray();
    }

    public function getCreatedOn(): DateTimeImmutable
    {
        return $this->created;
    }

    public function getLastUpdatedOn(): ?DateTimeImmutable
    {
        return $this->lastUpdated;
    }

    public function getCreated(): DateTimeImmutable
    {
        return $this->created;
    }

    public function setCreated(DateTimeImmutable $created): void
    {
        $this->created = $created;
    }

    public function setArchived(bool $archived): void
    {
        $this->archived = $archived;
    }
}

templates/tasks/contributors.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
    <div class="bg-white rounded shadow-sm py-2 mb-3">
        <div class="container">
            <h1>{{ task_list.title|title }}</h1>
            <p>created by <strong>{{ task_list.owner.email }}</strong> with contributions from: {{ task_list.contributors|map(contributor => contributor.email)|join(', ') }}</p>
            <p class="text-right"><small class="text-muted">created on {{ task_list.createdOn|date('d.m.Y H:i') }}</small></p>
        </div>
    </div>

    {{ form_start(form) }}
        <div class="col-sm-12">
            {{ form_row(form.contributor, {'label': 'Invite user' }) }}
        </div>
        <div class="col-sm-12">
            <div class="btn-group btn-group-lg">
                <button class="btn btn-outline-primary" type="submit">Add</button>
                <a href="{{ path('tasklist_show', {id: task_list.id}) }}" class="btn btn-outline-secondary">Go back</a>
            </div>
        </div>
    {{ form_end(form) }}

{% endblock %}

templates/tasks/index.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
    <form action="#" method="post" class="mb-4">
        <div class="row">
            <div class="col-sm-10">
                <label for="list_name" class="sr-only">List name</label>
                <input id="list_name" type="text" class="form-control form-control-lg" name="name" placeholder="Give your list a name">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Create a list</button>
            </div>
        </div>
    </form>
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link{% if app.request.query.get('filter') is null %} active bg-light{% endif %}" href="{{ path('tasklist_list') }}">All Lists</a></li>
        <li class="nav-item"><a class="nav-link{% if app.request.query.get('filter') == 'own' %} active bg-light{% endif %}" href="{{ path('tasklist_list', {filter: 'own'}) }}">My Lists</a></li>
        <li class="nav-item"><a class="nav-link{% if app.request.query.get('filter') == 'contributing' %} active bg-light{% endif %}" href="{{ path('tasklist_list', {filter: 'contributing'}) }}">Contributing Lists</a></li>
        <li class="nav-item"><a class="nav-link{% if app.request.query.get('filter') == 'active' %} active bg-light{% endif %}" href="{{ path('tasklist_list', {filter: 'active'}) }}">Active Lists</a></li>
        <li class="nav-item"><a class="nav-link{% if app.request.query.get('filter') == 'archived' %} active bg-light{% endif %}" href="{{ path('tasklist_list', {filter: 'archived'}) }}">Archived Lists</a></li>
    </ul>

    <div class="mt-4 mb-5">
        <div class="row">
            {% for task_list in task_lists %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ path('tasklist_show', {'id': task_list.id}) }}">{{ task_list.title|title }}</a></h5>
                            <p class="card-text">list with {{ task_list.items|length }} tasks</p>

                            <div class="d-flex justify-content-between align-items-baseline">
                                <div class="btn-group btn-group-sm mb-3 align-bottom">
                                    <a class="btn btn-outline-primary" href="{{ path('tasklist_show', {'id': task_list.id}) }}">show</a>
                                </div>
                                <p class="card-text"><small class="text-muted">
                                    {% if task_list.lastUpdatedOn is not null %}
                                        last updated {{ task_list.lastUpdatedOn|date('d.m.Y H:i') }}
                                    {% else %}
                                        created {{ task_list.createdOn|date('d.m.Y H:i') }}
                                    {% endif %}
                                </small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/tasks/index_summarized.html.twig
{% extends 'layout.html.twig' %}

{% block content %}

    <form action="{{ path('tasklist_create') }}" method="post" class="mb-4">
        <div class="row">
            <div class="col-sm-10">
                <label for="list_name" class="sr-only">List name</label>
                <input id="list_name" type="text" class="form-control form-control-lg" name="name" placeholder="Give your list a name">
            </div>
            <div class="col-sm-2">
                <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Create a list</button>
            </div>
        </div>
    </form>
    <ul class="nav nav-tabs">
        <li class="nav-item"><a class="nav-link active bg-light" href="{{ path('tasklist_list') }}">All Lists</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ path('tasklist_list', {filter: 'own'}) }}">My Lists</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ path('tasklist_list', {filter: 'contributing'}) }}">Contributing Lists</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ path('tasklist_list', {filter: 'active'}) }}">Active Lists</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ path('tasklist_list', {filter: 'archived'}) }}">Archived Lists</a></li>
    </ul>

    <div class="mt-4 mb-5">
        <div class="row">
            {% for list in lists %}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ path('tasklist_show', {'id': list.id}) }}">{{ list.name|title }}</a></h5>
                            <p class="card-text">list with {{ list.taskCount }} tasks</p>

                            <div class="d-flex justify-content-between align-items-baseline">
                                <div class="btn-group btn-group-sm mb-3 align-bottom">
                                    <a class="btn btn-outline-primary" href="{{ path('tasklist_show', {'id': list.id}) }}">show</a>
                                </div>
                                <p class="card-text"><small class="text-muted">
                                    {% if list.updated is not null %}
                                        last updated {{ list.updated|date('d.m.Y H:i') }}
                                    {% else %}
                                        created {{ list.created|date('d.m.Y H:i') }}
                                    {% endif %}
                                </small></p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/tasks/recent.html.twig
{% extends 'layout.html.twig' %}

{% block content %}

    <div class="list-group">
        {% for task in tasks %}
            <div class="list-group-item{% if task.done %} bg-light text-muted{% endif %}">
                <div class="d-flex justify-content-start align-items-baseline">
                    <form action="{{ path('tasklist_item_update', {'id': task.id}) }}" method="post" class="mr-3">
                        <div class="btn-group btn-group-sm">
                            <button class="btn {{ task.done ? 'btn-outline-secondary' : 'btn-primary' }}">{{ task.done ? 'reopen' : 'close' }}</button>
                        </div>
                    </form>
                    <strong>{{ task.summary|title }}</strong>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/tasks/show.html.twig
{% extends 'layout.html.twig' %}

{% block content %}

    <div class="{{ task_list.archived ? 'bg-dark text-muted' : 'bg-white' }} rounded shadow-sm pt-2 mb-3">
        <div class="container">
            <h1>{% if task_list.archived %}<span class="badge badge-secondary">archived</span>{% endif %} {{ task_list.title|title }}</h1>
            <p>created by <strong>{{ task_list.owner.email }}</strong> with contributions from: {{ task_list.contributors|map(contributor => contributor.email)|join(', ') }}</p>
            <div class="d-flex justify-content-between align-items-baseline">
                {% if task_list.archived == false %}
                <form action="{{ path('tasklist_archive', {id: task_list.id, version: task_list.version}) }}" method="post">
                    <div class="btn-group btn-group-sm mb-3 align-bottom">
                        <a href="{{ path('tasklist_contributors', {id: task_list.id}) }}" class="btn btn-outline-primary">Add Contributor</a>
                        <button type="submit" class="btn btn-outline-secondary">Archive list</button>
                    </div>
                </form>
                {% endif %}
                <p><small class="text-muted">created on {{ task_list.createdOn|date('d.m.Y H:i') }}</small></p>
            </div>
        </div>
    </div>

    <form action="{{ path('tasklist_add', {id: task_list.id}) }}" method="post" class="mb-4">
        <div class="row">
            <div class="col-lg-10 col-md-8">
                <label for="task_summary" class="sr-only">List name</label>
                <input id="task_summary" type="text" class="form-control form-control-lg" name="summary" placeholder="Enter your task summary">
            </div>
            <div class="col-lg-2 col-md-4">
                <button class="btn btn-outline-primary btn-lg btn-block" type="submit">Add task</button>
            </div>
        </div>
    </form>

    <div class="list-group">
        {% for task in task_list.items %}
            <div class="list-group-item{% if task.done %} bg-light text-muted{% endif %}">
                <div class="d-flex justify-content-start align-items-baseline">
                    <form action="{{ path('tasklist_item_update', {'id': task.id}) }}" method="post" class="mr-3">
                        <div class="btn-group btn-group-sm">
                            <button class="btn {{ task.done ? 'btn-outline-secondary' : 'btn-primary' }}">{{ task.done ? 'reopen' : 'close' }}</button>
                        </div>
                    </form>
                    <strong>{{ task.summary|title }}</strong>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}